source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-feed"
gem "jekyll-sitemap"
gem "jekyll-redirect-from"
gem "jemoji"
gem "webrick"
gem "connection_pool", "2.5.0"
gem "jekyll-gist"
gem "jekyll-paginate"
